### ISSUE TITLE
Modal presentation -> Rotate -> Dismiss

### ISSUE THREAD

**Issue by chrischute** [kukushi/SideMenu#64]
First off, great project! Simple and easy to use.

I had a layout issue caused by the following steps:

1. Modal presentation over the content view controller
2. Rotate the device
3. Dismiss the modally presented view
4. Now the content view is not sized properly

I traced these steps to `viewWillTransition` and specifically the following line: `self.contentContainerView.frame = self.contentFrame(visibility: self.isMenuRevealed)`. For me, `view.frame` is not correct and instead should use the `size` argument to `viewWillTransition` in `SideMenuController.swift`. I changed the line to the following: `self.contentContainerView.frame = CGRect(origin: .zero, size: size)`. This is probably a hack, but thought I'd bring it up in case you see the proper fix.

Best,
Chris

**Comment by kukushi** [comment]
Thanks for the detail description and hint.
You can try the fix on the develop branch.

**Comment by gsoykan** [comment]
![Simulator Screen Shot - iPhone 8 - 2019-07-09 at 11 31 53](https://user-images.githubusercontent.com/11638870/60872534-80da3680-a23d-11e9-9d89-06119f96952c.png)

I got this layout during the following situation: 

- First a viewController is pushed to the navigation and that rotates the screen horizontally
- Then when that viewController is popped up the rotation is going back to vertical (portrait)
- And then you can see the black portion in the screen shot which is part of SideMenuController because it has clear color. 

I Could not manage to solve the problem. Hope you can emulate the problem and fix.
Because of this I will not be able to use this project.
Nevertheless I really liked it. 
Best.

**Comment by psnt143** [comment]
how to show sidemenu open when Rotate the device?
